package main

import (
	"encoding/json"
	"fmt"
	"testing"
)

func TestImpl(t *testing.T) {
	s := CvmServer{}

	m := map[string]string{
		"PODID":        "0",
		"APPID":        "AAIAAAQAAgABAAAAEhb%2F%2F%2F%2BADgAAAAAAAAAAAAsAAAAAAAD%2FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbUf0Upcq79xkEEjsAssYX7oioeZM1xMj3hymBuio69JNNf8D%2FXJRWA%3D%3D",
		"CHAIN_ADDR":   "ws://192.168.110.205:9944",
		"WORKER_ADDR":  "192.168.110.205:8883",
		"NAME_SPACE":   "9621dde636de098b43efb0fa9b61facfe328f99d",
		"__FILES__":    "{\"0\":{\"K2\":\"4b33\"}}",
		"__ENCRYPTS__": "{\"0\":{\"K2\":0}}",
		"__DISKS__":    "{}",
	}
	bt, _ := json.Marshal(m)

	resp := s.start(&CrossRequest{env: bt})
	fmt.Println(string(resp.data))
}
